---
# handlers/main.yml
- name: Restart SSSD
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
