# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use CentOS 7 or CentOS 8 depending on your preference or need
  centos_version = "generic/centos9s"

  # Define the first VM
  config.vm.define "nebula" do |nebula|
    nebula.vm.box = centos_version
    nebula.vm.hostname = "nebula"
    nebula.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"  # Forward SSH port
  end

  # Define the second VM
  config.vm.define "cosmos" do |cosmos|
    cosmos.vm.box = centos_version
    cosmos.vm.hostname = "cosmos"
    cosmos.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"  # Forward SSH port
  end

  # Define the third VM
  config.vm.define "quasar" do |quasar|
    quasar.vm.box = centos_version
    quasar.vm.hostname = "quasar"
    quasar.vm.network "forwarded_port", guest: 22, host: 2224, id: "ssh"  # Forward SSH port
  end

  # Define the fourth VM
  config.vm.define "pulsar" do |pulsar|
    pulsar.vm.box = centos_version
    pulsar.vm.hostname = "pulsar"
    pulsar.vm.network "forwarded_port", guest: 22, host: 2225, id: "ssh"  # Forward SSH port
  end

  # Define the fifth VM
  config.vm.define "supernova" do |supernova|
    supernova.vm.box = centos_version
    supernova.vm.hostname = "supernova"
    supernova.vm.network "forwarded_port", guest: 22, host: 2226, id: "ssh"  # Forward SSH port
  end
end
