---
## CentOS tasks.
##
- name: Requirements for Python install
  when: python3_pyenv == None

  block:
    - name: Install addtional repos
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - https://centos7.iuscommunity.org/ius-release.rpm

    - name: Install system packages
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - python36u
        - python36u-devel
        - python36u-pip

    - name: Install pip
      become: true
      ansible.builtin.command: "{{ python3_command }} -m ensurepip"
- name: Requirements for pyenv install
  when: python3_pyenv != None
  block:
    - name: Install system packages for pyenv
      become: true
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - zlib-devel
        - openssl-devel
        - openssl-static
        - sqlite-devel
        - bzip2-devel
        - bzip2-libs
        - readline-devel
        - readline-static
