---
## Install Python using pyenv.
##
- name: Pyenv installation of Python
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.pyenv/bin"
  block:
    - name: Install pyenv
      block:
        - name: Download pyenv installer
          ansible.builtin.get_url:
            url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
            dest: "{{ python3_tmpdir }}"

        - name: Run pyenv installer
          ansible.builtin.command: bash pyenv-installer
          args:
            chdir: "{{ python3_tmpdir }}"

        - name: Update login file
          ansible.builtin.blockinfile:
            path: "{{ python3_bashrc }}"
            create: true
            block: |
              export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
              eval "$(pyenv init -)"
              eval "$(pyenv virtualenv-init -)"

        - name: Update pyenv
          ansible.builtin.command: pyenv update
    - name: Install Python
      block:
        - name: Install Python
          ansible.builtin.command: pyenv install {{ python3_pyenv }}
          args:
            creates: "{{ ansible_user_dir }}/.pyenv/versions/{{ python3_pyenv }}"

        - name: Pyenv rehash
          ansible.builtin.command: pyenv rehash
        - name: Define python3 command
          ansible.builtin.set_fact: # can't rely on changes to $PATH yet
            python3_command: "{{ ansible_user_dir }}/.pyenv/shims/{{ python3_command }}"
