---
## Tasks unique to Ubuntu.
##
- name: Requirements for Python install
  when: python3_pyenv == None

  block:
    - name: Install repositories
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        update_cache: true
      with_items:
        - ppa:deadsnakes/ppa

    - name: Install system packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3.6
        - python3.6-dev

    - name: Download pip installer
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "{{ python3_tmpdir }}/"

    - name: Install pip
      become: true
      ansible.builtin.command: "{{ python3_command }} get-pip.py"
      args:
        chdir: "{{ python3_tmpdir }}"

- name: Requirements for pyenv install
  when: python3_pyenv != None
  block:
    - name: Install system packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - libreadline-dev
        - zlib1g-dev
        - libssl-dev
        - libbz2-dev
        - libsqlite3-dev
