---
- name: Ensure all packages are up to date
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true

- name: Install Python 3
  ansible.builtin.dnf:
    name: python3
    state: present
  become: true
