---
- name: Install and start firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

# Ensure firewalld is started and enabled
- name: Ensure firewalld is started and enabled
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

# Allow Docker daemon port (2376) through firewall
- name: Allow Docker daemon port (2376) through firewall
  ansible.posix.firewalld:
    port: 2376/tcp
    permanent: true
    state: enabled
  notify:
    - Reload firewall

# Allow Docker Swarm management port (2377) through firewall
- name: Allow Docker Swarm management port (2377) through firewall
  ansible.posix.firewalld:
    port: 2377/tcp
    permanent: true
    state: enabled
  notify:
    - Reload firewall

# Allow Overlay network traffic port (4789) through firewall
- name: Allow Overlay network traffic port (4789) through firewall
  ansible.posix.firewalld:
    port: 4789/udp
    permanent: true
    state: enabled
  notify:
    - Reload firewall

# Allow Docker Swarm node communication ports (7946) through firewall (TCP)
- name: Allow Docker Swarm node communication ports (7946) through firewall
  ansible.posix.firewalld:
    port: 7946/tcp
    permanent: true
    state: enabled
  notify:
    - Reload firewall

# Allow Docker Swarm node communication ports (7946) through firewall (UDP)
- name: Allow Docker Swarm node communication ports (7946) through firewall
  ansible.posix.firewalld:
    port: 7946/udp
    permanent: true
    state: enabled
  notify:
    - Reload firewall

# Enable IP masquerading for Docker network
- name: Enable IP masquerading for Docker network
  ansible.posix.firewalld:
    zone: public
    masquerade: true
    permanent: true
    state: enabled
  notify:
    - Reload firewall
# Set SELinux in permissive mode temporarily (if needed)
- name: Set SELinux in permissive mode temporarily
  selinux:
    policy: targeted
    state: permissive

# Set DNS for Docker daemon (ensure no duplication)
- name: Set DNS for Docker daemon
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "dns": ["8.8.8.8", "8.8.4.4"]
      }
    mode: "0644"
    backup: true
  notify:
    - Restart Docker
