---
- name: Clean all yum cache
  ansible.builtin.command: yum clean all
- name: Install required packages for Docker
  ansible.builtin.dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  ansible.builtin.command: >
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Install container-selinux
  ansible.builtin.dnf:
    name: container-selinux
    state: present
  when: ansible_distribution_major_version is version('9', '<')

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure current user is added to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Check if Docker group exists
  ansible.builtin.getent:
    database: group
    key: docker
  register: docker_group

- name: Create Docker group if it doesn't exist
  ansible.builtin.group:
    name: docker
    state: present
  when: docker_group is not defined

- name: Change ownership of Docker socket to root:docker
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: "0660"

- name: Restart Docker service after permission changes
  ansible.builtin.systemd:
    name: docker
    state: restarted
