---
- name: Restart_network_services
  ansible.builtin.service:
    name: network
    state: restarted

- name: Restart_sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: Restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart_chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
