# .github/workflows/ansible-lint.yml
name: Lint and Restyle Ansible Files

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restyled
        uses: restyled-io/actions/setup@v4
        with:
          restylers: ansible-lint

      - name: Run Restyled for Ansible Lint
        run: |
          restyle apply
